/* Generated By:JavaCC: Do not edit this line. ProtocolsParserConstants.java */
package de.japes.parser;

public interface ProtocolsParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int PROTOCOL_NUMBER = 6;
  int PROTOCOL_NAME = 7;
  int UPPER_CASE_NAME = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"<SINGLE_LINE_COMMENT>\"",
    "<SINGLE_LINE_COMMENT>",
    "<PROTOCOL_NUMBER>",
    "<PROTOCOL_NAME>",
    "<UPPER_CASE_NAME>",
  };

}
