/* Generated By:JavaCC: Do not edit this line. ServicesParserConstants.java */
package de.japes.parser;

public interface ServicesParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int SERVICE_PORT = 6;
  int SERVICE_NAME = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"<SINGLE_LINE_COMMENT>\"",
    "<SINGLE_LINE_COMMENT>",
    "<SERVICE_PORT>",
    "<SERVICE_NAME>",
  };

}
