/**************************************************************************/
/*  NASTY - Network Analysis and STatistics Yielding                      */
/*                                                                        */
/*  Copyright (C) 2006 History Project, http://www.history-project.net    */
/*  History (HIgh-Speed neTwork mOniToring and analYsis) is a research    */
/*  project by the Universities of Tuebingen and Erlangen-Nuremberg,      */
/*  Germany                                                               */
/*                                                                        */
/*  Authors of NASTY are:                                                 */
/*      Christian Japes, University of Erlangen-Nuremberg                 */
/*      Thomas Schurtz, University of Tuebingen                           */
/*      David Halsband, University of Tuebingen                           */
/*      Gerhard Muenz <muenz@informatik.uni-tuebingen.de>,                */
/*          University of Tuebingen                                       */
/*      Falko Dressler <dressler@informatik.uni-erlangen.de>,             */
/*          University of Erlangen-Nuremberg                              */
/*                                                                        */
/*  This program is free software; you can redistribute it and/or modify  */
/*  it under the terms of the GNU General Public License as published by  */
/*  the Free Software Foundation; either version 2 of the License, or     */
/*  (at your option) any later version.                                   */
/*                                                                        */
/*  This program is distributed in the hope that it will be useful,       */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of        */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         */
/*  GNU General Public License for more details.                          */
/*                                                                        */
/*  You should have received a copy of the GNU General Public License     */
/*  along with this program; if not, write to the Free Software           */
/*  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA  */
/**************************************************************************/

/* Generated By:JavaCC: Do not edit this line. ConfigParserConstants.java */
package de.japes.parser.nasty;

public interface ConfigParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 1;
  int UDP_BUFFER_SIZE = 6;
  int DATABASE_NAME = 7;
  int DATABASE_SERVER = 8;
  int DATABASE_PORT = 9;
  int DATABASE_USER = 10;
  int DATABASE_PASS = 11;
  int DAYS_DETAILED_DATA = 12;
  int WEEKS_DAILY_DATA = 13;
  int TEXT = 14;
  int WHITESPACE = 15;
  int VALUE = 16;

  int DEFAULT = 0;
  int FOUND_OPTION = 1;

  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"<SINGLE_LINE_COMMENT>\"",
    "\"udp_buffer_size\"",
    "\"db_name\"",
    "\"db_server\"",
    "\"db_port\"",
    "\"db_user\"",
    "\"db_pass\"",
    "\"days_detailed_data\"",
    "\"weeks_daily_data\"",
    "<TEXT>",
    "<WHITESPACE>",
    "<VALUE>",
  };

}
