/* Generated By:JavaCC: Do not edit this line. ConfigParserConstants.java */
package de.japes.parser.nasty;

public interface ConfigParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 1;
  int UDP_BUFFER_SIZE = 6;
  int DATABASE_NAME = 7;
  int DATABASE_SERVER = 8;
  int DATABASE_PORT = 9;
  int DATABASE_USER = 10;
  int DATABASE_PASS = 11;
  int DAYS_DETAILED_DATA = 12;
  int WEEKS_DAILY_DATA = 13;
  int TEXT = 14;
  int WHITESPACE = 15;
  int VALUE = 16;

  int DEFAULT = 0;
  int FOUND_OPTION = 1;

  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"<SINGLE_LINE_COMMENT>\"",
    "\"udp_buffer_size\"",
    "\"db_name\"",
    "\"db_server\"",
    "\"db_port\"",
    "\"db_user\"",
    "\"db_pass\"",
    "\"days_detailed_data\"",
    "\"weeks_daily_data\"",
    "<TEXT>",
    "<WHITESPACE>",
    "<VALUE>",
  };

}
